
CREATE TABLE t_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(50)                             NOT NULL,
    email    VARCHAR(100),
    password VARCHAR(255),
    balance  DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_t_user PRIMARY KEY (id)
);

CREATE TABLE t_role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_t_role PRIMARY KEY (id)
);


CREATE TABLE t_user_role
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_t_user_role PRIMARY KEY (role_id, user_id)
);

ALTER TABLE t_user
    ADD CONSTRAINT uc_t_user_email UNIQUE (email);

ALTER TABLE t_user
    ADD CONSTRAINT uc_t_user_username UNIQUE (username);

ALTER TABLE t_user_role
    ADD CONSTRAINT fk_tuserol_on_role FOREIGN KEY (role_id) REFERENCES t_role (id);

ALTER TABLE t_user_role
    ADD CONSTRAINT fk_tuserol_on_user FOREIGN KEY (user_id) REFERENCES t_user (id);


CREATE TABLE t_review
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text       VARCHAR(255),
    rating     INTEGER                                 NOT NULL,
    user_id    BIGINT,
    product_id BIGINT,
    reviews    BIGINT,
    CONSTRAINT pk_t_review PRIMARY KEY (id)
);

ALTER TABLE t_review
    ADD CONSTRAINT FK_T_REVIEW_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES t_product (id);

ALTER TABLE t_review
    ADD CONSTRAINT FK_T_REVIEW_ON_REVIEWS FOREIGN KEY (reviews) REFERENCES t_product (id);

ALTER TABLE t_review
    ADD CONSTRAINT FK_T_REVIEW_ON_USER FOREIGN KEY (user_id) REFERENCE;

CREATE TABLE t_purchase
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT,
    product_id      BIGINT,
    purchaseDate    TIMESTAMP WITHOUT TIME ZONE,
    returned        BOOLEAN,
    isReturnExpired BOOLEAN,
    CONSTRAINT pk_t_purchase PRIMARY KEY (id)
);

ALTER TABLE t_purchase
    ADD CONSTRAINT FK_T_PURCHASE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES t_product (id);

ALTER TABLE t_purchase
    ADD CONSTRAINT FK_T_PURCHASE_ON_USER FOREIGN KEY (user_id) REFERENCES t_user (id);

CREATE TABLE t_product
(
    id               BIGINT           NOT NULL,
    name             VARCHAR(255),
    description      VARCHAR(255),
    company          BIGINT,
    instock          INTEGER          NOT NULL,
    price            DOUBLE PRECISION NOT NULL,
    quantity         INTEGER          NOT NULL,
    product_discount BIGINT,
    characteristics  VARCHAR(255),
    rating           DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_t_product PRIMARY KEY (id)
);

CREATE TABLE t_product_keyword
(
    Product_id BIGINT NOT NULL,
    keyword_id BIGINT NOT NULL
);

CREATE TABLE t_product_reviews
(
    Product_id BIGINT NOT NULL,
    reviews_id BIGINT NOT NULL
);

ALTER TABLE t_product_keyword
    ADD CONSTRAINT uc_t_product_keyword_keyword UNIQUE (keyword_id);

ALTER TABLE t_product_reviews
    ADD CONSTRAINT uc_t_product_reviews_reviews UNIQUE (reviews_id);

ALTER TABLE t_product
    ADD CONSTRAINT FK_T_PRODUCT_ON_COMPANY FOREIGN KEY (company) REFERENCES t_company (id);

ALTER TABLE t_product
    ADD CONSTRAINT FK_T_PRODUCT_ON_PRODUCT_DISCOUNT FOREIGN KEY (product_discount) REFERENCES t_discount (id);

ALTER TABLE t_product_keyword
    ADD CONSTRAINT fk_tprokey_on_keyword FOREIGN KEY (keyword_id) REFERENCES t_keywordn (id);

ALTER TABLE t_product_keyword
    ADD CONSTRAINT fk_tprokey_on_product FOREIGN KEY (Product_id) REFERENCES t_product (id);

ALTER TABLE t_product_reviews
    ADD CONSTRAINT fk_tprorev_on_product FOREIGN KEY (Product_id) REFERENCES t_product (id);

ALTER TABLE t_product_reviews
    ADD CONSTRAINT fk_tprorev_on_review FOREIGN KEY (reviews_id) REFERENCES t_review (id);

CREATE TABLE order_product
(
    order_id   BIGINT NOT NULL,
    product_id BIGINT NOT NULL
);

CREATE TABLE t_order
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT,
    totalPrice   DOUBLE PRECISION                        NOT NULL,
    purchaseDate date,
    returned     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_t_order PRIMARY KEY (id)
);

ALTER TABLE t_order
    ADD CONSTRAINT FK_T_ORDER_ON_USER FOREIGN KEY (user_id) REFERENCES t_user (id);

ALTER TABLE order_product
    ADD CONSTRAINT fk_ordpro_on_order FOREIGN KEY (order_id) REFERENCES t_order (id);

ALTER TABLE order_product
    ADD CONSTRAINT fk_ordpro_on_product FOREIGN KEY (product_id) REFERENCES t_product (id);

CREATE TABLE t_notification
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title   VARCHAR(255),
    date    date,
    content VARCHAR(255),
    user_id BIGINT,
    CONSTRAINT pk_t_notification PRIMARY KEY (id)
);

ALTER TABLE t_notification
    ADD CONSTRAINT FK_T_NOTIFICATION_ON_USER FOREIGN KEY (user_id) REFERENCES t_user (id);

CREATE TABLE t_keywordn
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    keywords BIGINT,
    CONSTRAINT pk_t_keywordn PRIMARY KEY (id)
);

CREATE TABLE t_keywordn_product
(
    Keyword_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT pk_t_keywordn_product PRIMARY KEY (Keyword_id, product_id)
);

ALTER TABLE t_keywordn_product
    ADD CONSTRAINT uc_t_keywordn_product_product UNIQUE (product_id);

ALTER TABLE t_keywordn
    ADD CONSTRAINT FK_T_KEYWORDN_ON_KEYWORDS FOREIGN KEY (keywords) REFERENCES t_product (id);

ALTER TABLE t_keywordn_product
    ADD CONSTRAINT fk_tkeypro_on_keyword FOREIGN KEY (Keyword_id) REFERENCES t_keywordn (id);

ALTER TABLE t_keywordn_product
    ADD CONSTRAINT fk_tkeypro_on_product FOREIGN KEY (product_id) REFERENCES t_product (id);

CREATE TABLE discount_product
(
    discount_id BIGINT NOT NULL,
    product_id  BIGINT NOT NULL
);

CREATE TABLE t_discount
(
    id             BIGINT  NOT NULL,
    discountVolume INTEGER NOT NULL,
    durationInDays INTEGER NOT NULL,
    CONSTRAINT pk_t_discount PRIMARY KEY (id)
);

ALTER TABLE discount_product
    ADD CONSTRAINT fk_dispro_on_discount FOREIGN KEY (discount_id) REFERENCES t_discount (id);

ALTER TABLE discount_product
    ADD CONSTRAINT fk_dispro_on_product FOREIGN KEY (product_id) REFERENCES t_product (id);

CREATE TABLE t_company
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    companyName        VARCHAR(255),
    companyDescription VARCHAR(255),
    companyLogo        VARCHAR(255),
    commission         DOUBLE PRECISION                        NOT NULL,
    isActivated        BOOLEAN                                 NOT NULL,
    isFrozen           BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_t_company PRIMARY KEY (id)
);